name: 🧩 Co-Maintainer Application
description: Apply to become a co-maintainer of the TigerByte open-source project 🐯
title: "Co-Maintainer Application: [Your Name]"
labels: ["co-maintainer", "application", "open-source"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐯 Welcome to the TigerByte Co-Maintainer Application!

        Thank you for your interest in helping maintain and grow **TigerByte**, an educational open-source interpreter project built for learners and contributors alike.

        ⚡ **About This Role**
        - This is a **volunteer** position — unpaid but community-driven.
        - You’ll help with project management, reviewing PRs, guiding contributors, writing docs, and shaping future features.
        - Commitment is flexible, but we ask for consistent engagement.

        🧡 **Let’s grow TigerByte together!**

  - type: input
    id: name
    attributes:
      label: Full Name
      description: Your full name (as you’d like it displayed in the contributors list).
      placeholder: e.g., Alex Tanaka
      required: true

  - type: input
    id: github_username
    attributes:
      label: GitHub Username
      description: Please provide your GitHub handle.
      placeholder: e.g., @alex-tanaka
      required: true

  - type: input
    id: timezone
    attributes:
      label: Timezone
      description: Include your time zone (e.g., UTC+8, PST, EST, etc.)
      placeholder: e.g., UTC+9 (Japan Standard Time)
      required: true

  - type: textarea
    id: availability
    attributes:
      label: Availability
      description: What days/times are you generally available for check-ins or sync-ups (in your local time)?
      placeholder: e.g., Weekends (Sat/Sun), or weekdays after 7 PM
      required: true

  - type: dropdown
    id: english_level
    attributes:
      label: English Communication Level
      description: Please select your comfort level with English communication.
      options:
        - Beginner
        - Intermediate
        - Advanced
        - Fluent / Native
      required: true

  - type: textarea
    id: skills
    attributes:
      label: Current Skills
      description: What technical or soft skills do you currently have that could help the TigerByte project?
      placeholder: e.g., Python, Git/GitHub, Documentation, Testing, Mentoring
      required: true

  - type: textarea
    id: learning_goals
    attributes:
      label: Skills You Want to Develop
      description: What would you like to learn or strengthen through this project?
      placeholder: e.g., Writing interpreters, contributing to open source, managing contributors
      required: false

  - type: dropdown
    id: commitment
    attributes:
      label: Commitment Duration
      description: How long can you commit to being a co-maintainer?
      options:
        - 3 months
        - 6 months
        - 1 year
        - Long-term (open-ended)
      required: true

  - type: checkboxes
    id: volunteer_acknowledgment
    attributes:
      label: Volunteer Acknowledgment
      description: Please confirm that you understand this is a volunteer open-source co-maintainer role.
      options:
        - label: I understand this is a volunteer (unpaid) role focused on collaboration, learning, and community growth.
      required: true

  - type: checkboxes
    id: syncup
    attributes:
      label: Team Communication
      description: Are you comfortable joining brief online sync-ups or check-ins (text or voice, weekly or bi-weekly)?
      options:
        - label: Yes, I’m okay with regular short sync-ups
        - label: Prefer async communication only
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why Do You Want to Be a Co-Maintainer?
      description: Share what motivates you to help lead TigerByte.
      placeholder: e.g., I love educational open-source projects and want to help others learn Python while growing my own skills.
      required: true

  - type: textarea
    id: ideas
    attributes:
      label: Ideas or Vision
      description: Do you have any suggestions or visions for improving TigerByte or expanding it in the future?
      placeholder: e.g., Add syntax highlighting, improve debug mode, build a learning wiki, add code examples
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        🐾 **Next Steps:**
        - After submitting, the TigerByte maintainer will review your application.
        - If it’s a good fit, you’ll be invited for a brief discussion or onboarding.
        - Thank you again for your interest and passion for open source 💛
       ⭐ *Optional: Don’t forget to star the repo to show your support!*
